server:
  port: 8080
  shutdown: graceful
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

application:
  services:
    airport-info-system: 127.0.0.1:8089

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  main:
    cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 5s
